-- script that creates the database hbtn_0d_usa and the table states (in the database hbtn_0d_usa)
-- states: id unique autogenerated no null as primary key
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(id int NOT NULL AUTO_INCREMENT, name VARCHAR(256) NOT NULL, PRIMARY KEY (id));
